drop table if exists accounts; 

create table accounts (
	id int generated by default as identity, 
	name varchar(100) not null, 
	balance dec(15,2) not null, 
	primary key(id)
); 

insert into accounts(name,balance) 
values('Bob',10000); 

insert into accounts(name,balance)
values('Alice',10000); 

select * from accounts; 

/*
creates a stored procedure names transfer that transfers a specified 
amount of money from one account to another 
*/
create or replace procedure transfer(
	sender int, 
	receiver int, 
	amount dec
)
language plpgsql
as $$
begin 
	-- subtracting the amount from sender's account
	update accounts 
	set balance = balance - amount
	where id = sender; 
	
	-- adding the amount to the receiver's account
	update accounts 
	set balance = balance + amount 
	where id = receiver;
	
	commit; 
end;$$

/*
 How to call a stored procedure? 
 call stored_procedure_name(argument_list); 
 */

call transfer(1,2,1000);


